export const buttonsName = {
	anchor: "anchor",
	backgroundColor: "background-color",
	blockQuote: "block-quote",
	bold: "bold",
	codeBlock: "code-block",
	color: "color",
	customComponent: "custom-component",
	fontFamily: "font-family",
	fontSize: "font-size",
	historyBack: "history-back",
	historyForward: "history-forward",
	image: "image",
	indentation: "indentation",
	italic: "italic",
	letterSpacing: "letter-spacing",
	lineHeight: "line-height",
	list: "list",
	removeFormat: "remove-format",
	strikethrough: "strikethrough",
	symbol: "symbol",
	table: "table",
	lineTagName: "line-tag-name",
	textAlign: "text-align",
	underline: "underline",
} as const;
